[package]
name = "mailnews_string_glue"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
icu_normalizer = { version = "2.1.1" }
nserror = { path = "../../../xpcom/rust/nserror" }
nsstring = { path = "../../../xpcom/rust/nsstring" }
