trust-domain: comm
project-repo-param-prefix: comm_
product-dir: comm/mail

treeherder:
    group-names:
        'X': 'Xpcshell tests'
        'Z': 'MozMill tests'
        'I': 'Docker Image Builds'
        'TL': 'Toolchain builds for Linux 64-bits'
        'TM': 'Toolchain builds for OSX'
        'TMW': 'Toolchain builds for Windows MinGW'
        'TW32': 'Toolchain builds for Windows 32-bits'
        'TW64': 'Toolchain builds for Windows 64-bits'
        'Deb7': 'Packages for Debian 7'
        'Deb7-32': 'Packages for Debian 7 32-bits'
        'Deb9': 'Packages for Debian 9'
        'Fetch-URL': 'Fetch and store content'
        'L10n': 'Localised Repacks'
        'L10n-Rpk': 'Localized Repackaged Repacks'
        'ms': 'Complete MAR signing'
        'MSI': 'Repack installers into MSIs'
        'MSIs': 'Signing of Repacked installers of MSIs'
        'rs': 'Repackage signing'
        'BMR-L10n': 'Beetmover repackages for locales'
        'c-Up': 'Balrog submission of complete updates'
        'cs': 'Checksum signing'
        'BMcs': 'Beetmover checksums,'
        'Rel': 'Release promotion'
        'css': 'Checksum signing for source'
        'BMcss': 'Beetmover checksums for source'
        'UV': 'Update verify'

index:
    products:
        - thunderbird

try:
    ridealong-builds: {}

release-promotion:
    products:
        - 'thunderbird'
    flavors:
        promote_thunderbird:
            product: thunderbird
            target-tasks-method: promote_desktop
        push_thunderbird:
            product: thunderbird
            target-tasks-method: push_desktop
        ship_thunderbird:
            product: thunderbird
            target-tasks-method: ship_desktop
            version-bump: true

scriptworker:
    scope-prefix: 'project:comm:thunderbird:releng'

    worker-types:
        'scriptworker-prov-v1/tb-depsigning':
            - 'project:comm:thunderbird:releng:signing:cert:dep-signing'
        'scriptworker-prov-v1/tb-signing-v1':
            - 'project:comm:thunderbird:releng:signing:cert:nightly-signing'
            - 'project:comm:thunderbird:releng:signing:cert:release-signing'
        'scriptworker-prov-v1/tb-beetmover-dev':
            - 'project:comm:thunderbird:releng:beetmover:bucket:dep'
        'scriptworker-prov-v1/tb-beetmover-v1':
            - 'project:comm:thunderbird:releng:beetmover:bucket:nightly'
            - 'project:comm:thunderbird:releng:beetmover:bucket:release'
        'scriptworker-prov-v1/tb-balrog-dev':
            - 'project:comm:thunderbird:releng:balrog:server:dep'
        'scriptworker-prov-v1/tb-balrog-v1':
            - 'project:comm:thunderbird:releng:balrog:server:nightly'
            - 'project:comm:thunderbird:releng:balrog:server:beta'
            - 'project:comm:thunderbird:releng:balrog:server:release'

partner:
    release: {}
    staging: {}
