# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
trust-domain: comm
project-repo-param-prefix: comm_
product-dir: comm/mail

treeherder:
    group-names:
        'X': 'Xpcshell tests'
        'I': 'Docker Image Builds'
        'TL': 'Toolchain builds for Linux 64-bits'
        'TM': 'Toolchain builds for OSX'
        'TMW': 'Toolchain builds for Windows MinGW'
        'TW32': 'Toolchain builds for Windows 32-bits'
        'TW64': 'Toolchain builds for Windows 64-bits'
        'Deb7': 'Packages for Debian 7'
        'Deb7-32': 'Packages for Debian 7 32-bits'
        'Deb9': 'Packages for Debian 9'
        'Deb10': 'Packages for Debian 10'
        'Fetch': 'Fetch and store content'
        'L10n': 'Localised Repacks'
        'L10n-Rpk': 'Localized Repackaged Repacks'
        'M': 'Mochitests'
        'p': 'Partial generation'
        'ps': 'Partials signing'
        'ms': 'Complete MAR signing'
        'MSI': 'Repack installers into MSIs'
        'MSIs': 'Signing of Repacked installers of MSIs'
        'rs': 'Repackage signing'
        'BM': 'Beetmover'
        'BMR': 'Beetmover repackages'
        'c-Up': 'Balrog submission of complete updates'
        'cs': 'Checksum signing'
        'BMcs': 'Beetmover checksums,'
        'Rel': 'Release promotion'
        'css': 'Checksum signing for source'
        'BMcss': 'Beetmover checksums for source'
        'UV': 'Update verify'

index:
    products:
        - thunderbird

try:
    ridealong-builds: {}

release-promotion:
    products:
        - 'thunderbird'
    flavors:
        promote_thunderbird:
            product: thunderbird
            target-tasks-method: promote_desktop
            partial-updates: true
        push_thunderbird:
            product: thunderbird
            target-tasks-method: push_desktop
            partial-updates: true
        ship_thunderbird:
            product: thunderbird
            target-tasks-method: ship_desktop
            version-bump: true
            partial-updates: true

scriptworker:
    scope-prefix: 'project:comm:thunderbird:releng'

partner-urls:
    release-partner-repack: {}
    release-eme-free-repack: {}

task-priority:
    by-project:
        'comm-esr68': 'very-high'
        'comm-beta': 'high'
        'comm-central': 'medium'
        'default': 'low'

taskgraph:
    register: comm_taskgraph:register
    decision-parameters: 'comm_taskgraph:get_decision_parameters'

workers:
    aliases:
        b-linux.*:
            provisioner: 'comm-{level}'
            implementation: docker-worker
            os: linux
            worker-type: '{alias}'
        b-win2012:
            provisioner: 'comm-{level}'
            implementation: generic-worker
            os: windows
            worker-type: '{alias}'
        images:
            provisioner: 'comm-{level}'
            implementation: docker-worker
            os: linux
            worker-type: '{alias}'
        balrog:
            provisioner: scriptworker-k8s
            implementation: balrog
            os: scriptworker
            worker-type:
                by-release-level:
                    production: comm-3-balrog
                    staging: comm-1-balrog
        bouncer:
            provisioner: scriptworker-k8s
            # Note that this implementation doesn't correspond with a
            # payload_builder, there are several `bouncer-*` implementations.
            implementation: bouncer
            os: scriptworker
            worker-type:
                by-release-level:
                    production: comm-3-bouncer
                    staging: comm-1-bouncer
        beetmover:
            provisioner: scriptworker-k8s
            implementation: beetmover
            os: scriptworker
            worker-type:
                by-release-level:
                    production: comm-3-beetmover
                    staging: comm-1-beetmover
        linux-depsigning:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: linux
            worker-type: comm-t-signing
        linux-signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: linux
            worker-type:
                by-release-level:
                    production: comm-3-signing
                    staging: comm-t-signing
        mac-depsigning:
            provisioner: scriptworker-prov-v1
            implementation: scriptworker-iscript
            os: macosx
            worker-type: tb-depsigning-mac-v1
        mac-signing:
            provisioner: scriptworker-prov-v1
            implementation: scriptworker-iscript
            os: macosx
            worker-type:
                by-release-level:
                    production: tb-signing-mac-v1
                    staging: tb-depsigning-mac-v1
        tree:
            provisioner: scriptworker-k8s
            implementation: treescript
            os: scriptworker
            worker-type:
                by-release-level:
                    production: comm-3-tree
                    staging: comm-1-tree
        t-linux(-large|-xlarge):
            provisioner: comm-t
            implementation: docker-worker
            os: linux
            worker-type: '{alias}'
        t-osx-1010:
            provisioner: releng-hardware
            implementation: generic-worker
            os: macosx
            worker-type: 'gecko-{alias}'
        t-osx-1014:
            provisioner: releng-hardware
            implementation: generic-worker
            os: macosx
            worker-type: 'gecko-{alias}'
        t-win.*:
            provisioner: comm-t
            implementation: generic-worker
            os: windows
            worker-type: '{alias}'
        succeed:
            provisioner: built-in
            implementation: succeed
            os: none
            worker-type: succeed
        misc:
            provisioner: comm-t
            implementation: docker-worker
            os: linux
            worker-type: misc

mac-notarization:
    mac-behavior:
        by-release-type:
            nightly.*: mac_notarize
            beta.*: mac_notarize
            release.*: mac_notarize
            default: mac_sign_and_pkg
    mac-entitlements:
        by-platform:
            macosx64.*:
                by-release-level:
                    production: comm/build/macosx/hardenedruntime/production.entitlements.xml
                    default: comm/build/macosx/hardenedruntime/developer.entitlements.xml
            default: ''
