[package]
name = "graph_xpcom"
version = "0.1.0"
edition = "2021"

[dependencies]
xpcom = { version = "0.1.0", path = "../../../xpcom/rust/xpcom" }
xpcom_async = { version = "0.1.0", path = "../xpcom_async" }
