# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
# This file contains exhaustive information about all the release artifacts that
# are needed within a type of release.
#
# Structure
# --------
# `bucket_paths`          -- prefix to be used per product to correctly access our buckets
# `default_locales`       -- list of locales to be used when composing upstream artifacts or the list of
#                      destinations. If given an empty locale, it uses these locales instead.
# `tasktype_map`          -- mapping between task reference and task type, particularly useful when
#                      composing the upstreamArtifacts for scriptworker.
# `platform_names`        -- various platform mappings used in reckoning artifacts or other paths
# `default`               -- a default entry, which the mappings extend and override in such a way that
#                      final path full-destinations will be a concatenation of the following:
#                      `bucket_paths`, `destinations`, `locale_prefix`, `pretty_name`
# `mapping`               -- the main section defining all artifacts to be archived
#
# Per-artifact fields (used within `mapping`):
# `from`                  -- specifies the dependency(ies) from which to expect the particular artifact
# `all_locales`           -- boolean argument to specify whether that particular artifact is to be expected
#                      for all locales or just the default one
# `description`           -- brief summary of what that artifact is
# `locale_prefix`         -- prefix to be used in the final destination paths, whether that's for default locale or not
# `source_path_modifier`  -- any parent dir that might be used in between artifact prefix and filename at source location
#                            for example `public/build` vs `public/build/ach/`.
# `destinations`          -- final list of directories where to push the artifacts
# `pretty_name`           -- the final name the artifact will have at destination
# `checksums_path`        -- the name to identify one artifact within the checksums file
# `not_for_platforms`     -- filtering option to avoid associating an artifact with a specific platform
# `only_for_platforms`    -- filtering option to exclusively include the association of an artifact for a specific platform
# `partials_only`         -- filtering option to avoid associating an artifact unless this flag is present
# `update_balrog_manifest`-- flag needed downstream in beetmover jobs to reckon the balrog manifest
# `from_buildid`          -- flag needed downstream in beetmover jobs to reckon the balrog manifest

bucket_paths:
    - pub/thunderbird/nightly
default_locales:
    - en-US
tasktype_map:
    build: build
    signing: signing
    mar-signing: signing
    partials-signing: signing
    repackage: repackage
    repackage-signing: repackage
    repackage-signing-msi: repackage
    repackage-signing-shippable-l10n-msix: signing
    repackage-deb: repackage
    repackage-deb-l10n: repackage
platform_names:
    filename_platform:
        by-platform:
            linux64-shippable: 'linux-x86_64'
            linux64-asan-reporter-shippable: 'linux-x86_64-asan-reporter'
            macosx64-shippable: 'mac'
            win32-shippable: 'win32'
            win64-shippable: 'win64'
            win64-asan-reporter-shippable: 'win64-asan-reporter'
    stage_platform:
        by-platform:
            linux64-shippable: 'linux64'
            linux64-asan-reporter-shippable: 'linux-x86_64-asan-reporter'
            macosx64-shippable: 'macosx64'
            win32-shippable: 'win32'
            win64-shippable: 'win64'
            win64-asan-reporter-shippable: 'win64-asan-reporter'

default: &default
    from:
        - build
    all_locales: false
    description: "TO_BE_OVERRIDDEN"
    locale_prefix: ''
    source_path_modifier:
        by-locale:
            default: '${locale}'
            en-US: ''
    destinations:
        by-locale:
            en-US:
                - ${year}/${month}/${upload_date}-${branch}
                - latest-${branch}
            default:
                - ${year}/${month}/${upload_date}-${branch}-l10n
                - latest-${branch}-l10n

mapping:
    buildhub.json:
        <<: *default
        description: "Build related information to be consumed by Buildhub service"
        pretty_name: thunderbird-${version}.${locale}.${filename_platform}.buildhub.json
        checksums_path: thunderbird-${version}.${locale}.${filename_platform}.buildhub.json
        destinations:
            by-locale:
                en-US:
                    - ${year}/${month}/${upload_date}-${branch}
                    - latest-${branch}
                    - latest-${branch}-l10n
                default:
                    - ${year}/${month}/${upload_date}-${branch}-l10n
                    - latest-${branch}-l10n
    KEY:
        <<: *default
        from:
            - signing
        description: "Public side of the key that was used to sign the release artifacts"
        pretty_name: KEY
        checksums_path: KEY
        only_for_platforms:
            - linux64-shippable
        destinations:
            - ${year}/${month}/${upload_date}-${branch}
            - ${year}/${month}/${upload_date}-${branch}-l10n
            - latest-${branch}
            - latest-${branch}-l10n
    target.crashreporter-symbols.zip:
        <<: *default
        description: "Crashreporter symbols to be consumed by Socorro"
        pretty_name: thunderbird-${version}.${locale}.${filename_platform}.crashreporter-symbols.zip
        checksums_path: thunderbird-${version}.${locale}.${filename_platform}.crashreporter-symbols.zip
        not_for_platforms:
            - linux64-asan-reporter-shippable
            - win64-asan-reporter-shippable
    target.json:
        <<: *default
        description: "Various compile and moz_app flags baked together in a json file"
        pretty_name: thunderbird-${version}.${locale}.${filename_platform}.json
        checksums_path: thunderbird-${version}.${locale}.${filename_platform}.json
    target.mozinfo.json:
        <<: *default
        description: "Various compile and moz_app flags baked together in a json file"
        pretty_name: thunderbird-${version}.${locale}.${filename_platform}.mozinfo.json
        checksums_path: thunderbird-${version}.${locale}.${filename_platform}.mozinfo.json
    target.txt:
        <<: *default
        description: "File containing buildid and revision"
        pretty_name: thunderbird-${version}.${locale}.${filename_platform}.txt
        checksums_path: thunderbird-${version}.${locale}.${filename_platform}.txt
    target_info.txt:
        <<: *default
        description: "File containing the buildID"
        pretty_name: thunderbird-${version}.${locale}.${filename_platform}_info.txt
        checksums_path: thunderbird-${version}.${locale}.${filename_platform}_info.txt
    mozharness.zip:
        <<: *default
        description: "File containing the mozharness set of scripts and configuration used by various automation tools"
        pretty_name: mozharness.zip
        checksums_path: mozharness.zip
    target.jsshell.zip:
        <<: *default
        description: "Set of shells to allow test snippets of Javascript code without needing to reload the page"
        pretty_name: jsshell-${filename_platform}.zip
        checksums_path: jsshell-${filename_platform}.zip
        not_for_platforms:
            - linux64-asan-reporter-shippable
            - win64-asan-reporter-shippable
    target.langpack.xpi:
        <<: *default
        all_locales: true
        description: "Localized repack that grabs a packaged en-US Thunderbird and repackages it as locale-specific Thunderbird"
        from:
            - build
        only_for_platforms:
            - linux64-shippable
            - linux64-asan-reporter-shippable
            - macosx64-shippable
            - win64-shippable
            - win32-shippable
            - win64-asan-reporter-shippable
        pretty_name: thunderbird-${version}.${locale}.langpack.xpi
        checksums_path: thunderbird-${version}.${locale}.langpack.xpi
        destinations:
            by-locale:
                en-US:
                    - ${year}/${month}/${upload_date}-${branch}
                    - latest-${branch}
                default:
                    - ${year}/${month}/${upload_date}-${branch}-l10n/${filename_platform}/xpi
                    - latest-${branch}-l10n/${filename_platform}/xpi
    target.langpack.deb:
        <<: *default
        all_locales: true
        description: "langpack.xpi repackaged as a .deb"
        from:
            - repackage-deb-l10n
        only_for_platforms:
            - linux-shippable
            - linux64-shippable
        pretty_name: thunderbird-${version}.${locale}.langpack.deb
        checksums_path: thunderbird-${version}.${locale}.langpack.deb
        destinations:
            by-locale:
                en-US:
                    - ${year}/${month}/${upload_date}-${branch}
                    - latest-${branch}
                default:
                    - ${year}/${month}/${upload_date}-${branch}-l10n/${filename_platform}/deb-l10n
                    - latest-${branch}-l10n/${filename_platform}/deb-l10n
    mar:
        <<: *default
        description: "Alongside `mbsdiff`, a tool used to generate partials"
        source_path_modifier: 'host/bin'
        pretty_name: mar
        checksums_path: mar
        not_for_platforms:
            - win32-shippable
            - win64-shippable
            - win64-asan-reporter-shippable
        destinations:
            - ${year}/${month}/${upload_date}-${branch}/mar-tools/${stage_platform}
            - latest-${branch}/mar-tools/${stage_platform}
    mbsdiff:
        <<: *default
        description: "Alongside `mar`, a tool used to generate partials"
        source_path_modifier: 'host/bin'
        pretty_name: mbsdiff
        checksums_path: mbsdiff
        not_for_platforms:
            - win32-shippable
            - win64-shippable
            - win64-asan-reporter-shippable
        destinations:
            - ${year}/${month}/${upload_date}-${branch}/mar-tools/${stage_platform}
            - latest-${branch}/mar-tools/${stage_platform}
    target.tar.xz:
        <<: *default
        description: "Main installer for Linux platforms"
        all_locales: true
        from:
            - signing
        only_for_platforms:
            - linux64-shippable
            - linux64-asan-reporter-shippable
        pretty_name: thunderbird-${version}.${locale}.${filename_platform}.tar.xz
        checksums_path: thunderbird-${version}.${locale}.${filename_platform}.tar.xz
        destinations:
            by-locale:
                en-US:
                    - ${year}/${month}/${upload_date}-${branch}
                    - latest-${branch}
                    - latest-${branch}-l10n
                default:
                    - ${year}/${month}/${upload_date}-${branch}-l10n
                    - latest-${branch}-l10n
    target.tar.xz.asc:
        <<: *default
        description: "Detached signature for the checksums file"
        all_locales: true
        from:
            - signing
        only_for_platforms:
            - linux64-shippable
            - linux64-asan-reporter-shippable
        pretty_name: thunderbird-${version}.${locale}.${filename_platform}.tar.xz.asc
        checksums_path: thunderbird-${version}.${locale}.${filename_platform}.tar.xz.asc
        destinations:
            by-locale:
                en-US:
                    - ${year}/${month}/${upload_date}-${branch}
                    - latest-${branch}
                    - latest-${branch}-l10n
                default:
                    - ${year}/${month}/${upload_date}-${branch}-l10n
                    - latest-${branch}-l10n
    target.pkg:
        <<: *default
        description: "Main package installer for Mac OS X platforms"
        all_locales: true
        from:
            - signing
        only_for_platforms:
            - macosx64-shippable
        pretty_name: thunderbird-${version}.${locale}.${filename_platform}.pkg
        checksums_path: thunderbird-${version}.${locale}.${filename_platform}.pkg
        destinations:
            by-locale:
                en-US:
                    - ${year}/${month}/${upload_date}-${branch}
                    - latest-${branch}
                    - latest-${branch}-l10n
                default:
                    - ${year}/${month}/${upload_date}-${branch}-l10n
                    - latest-${branch}-l10n
    target.dmg:
        <<: *default
        description: "Main package installer for Mac OS X platforms"
        all_locales: true
        from:
            - repackage
        only_for_platforms:
            - macosx64-shippable
        pretty_name: thunderbird-${version}.${locale}.${filename_platform}.dmg
        checksums_path: thunderbird-${version}.${locale}.${filename_platform}.dmg
        destinations:
            by-locale:
                en-US:
                    - ${year}/${month}/${upload_date}-${branch}
                    - latest-${branch}
                    - latest-${branch}-l10n
                default:
                    - ${year}/${month}/${upload_date}-${branch}-l10n
                    - latest-${branch}-l10n
    target.zip:
        <<: *default
        description: "Main package installer for Windows platforms"
        all_locales: true
        from:
            - signing
        only_for_platforms:
            - win64-shippable
            - win32-shippable
            - win64-asan-reporter-shippable
        pretty_name: thunderbird-${version}.${locale}.${filename_platform}.zip
        checksums_path: thunderbird-${version}.${locale}.${filename_platform}.zip
    target.installer.exe:
        <<: *default
        description: "Main installer for Windows platforms"
        all_locales: true
        from:
            - repackage-signing
        only_for_platforms:
            - win64-shippable
            - win32-shippable
            - win64-asan-reporter-shippable
        pretty_name: thunderbird-${version}.${locale}.${filename_platform}.installer.exe
        checksums_path: thunderbird-${version}.${locale}.${filename_platform}.installer.exe
        destinations:
            by-locale:
                en-US:
                    - ${year}/${month}/${upload_date}-${branch}
                    - latest-${branch}
                    - latest-${branch}-l10n
                default:
                    - ${year}/${month}/${upload_date}-${branch}-l10n
                    - latest-${branch}-l10n
    target.installer.msi:
        <<: *default
        description: "Windows installer for MSI platform"
        all_locales: true
        from:
            - repackage-signing-msi
        only_for_platforms:
            - win64-shippable
            - win32-shippable
        pretty_name: thunderbird-${version}.${locale}.${filename_platform}.installer.msi
        checksums_path: thunderbird-${version}.${locale}.${filename_platform}.installer.msi
        destinations:
            by-locale:
                en-US:
                    - ${year}/${month}/${upload_date}-${branch}
                    - latest-${branch}
                    - latest-${branch}-l10n
                default:
                    - ${year}/${month}/${upload_date}-${branch}-l10n
                    - latest-${branch}-l10n
    target.installer.msix:
        <<: *default
        description: "Windows MSIX installer"
        all_locales: true
        from:
            - repackage-signing-shippable-l10n-msix
        only_for_platforms:
            - win64-shippable
            - win32-shippable
        pretty_name: thunderbird-${version}.multi.${filename_platform}.installer.msix
        checksums_path: thunderbird-${version}.multi.${filename_platform}.installer.msix
        destinations:
            - ${year}/${month}/${upload_date}-${branch}
            - latest-${branch}
            - latest-${branch}-l10n
    target.deb:
        <<: *default
        description: "Thunderbird as a .deb package"
        from:
            - repackage-deb
        only_for_platforms:
            - linux64-shippable
        pretty_name: thunderbird-${version}.${locale}.${filename_platform}.deb
        checksums_path: thunderbird-${version}.${locale}.${filename_platform}.deb
        update_balrog_manifest: false
        destinations:
            - ${year}/${month}/${upload_date}-${branch}
            - latest-${branch}
    target.complete.mar:
        <<: *default
        description: "The main installer we ship our mobile products baked within"
        all_locales: true
        from:
            - mar-signing
        pretty_name: thunderbird-${version}.${locale}.${filename_platform}.complete.mar
        checksums_path: thunderbird-${version}.${locale}.${filename_platform}.complete.mar
        update_balrog_manifest: true
        destinations:
            by-locale:
                en-US:
                    - ${year}/${month}/${upload_date}-${branch}
                    - latest-${branch}
                    - latest-${branch}-l10n
                default:
                    - ${year}/${month}/${upload_date}-${branch}-l10n
                    - latest-${branch}-l10n
    ${partial}:
        <<: *default
        description: "Partials MAR files to serve as updates"
        all_locales: true
        from:
            - partials-signing
        partials_only: true
        pretty_name: thunderbird-${branch}-${version}-${filename_platform}-${locale}-${from_buildid}-${buildid}.partial.mar
        checksums_path: thunderbird-${branch}-${version}-${filename_platform}-${locale}-${from_buildid}-${buildid}.partial.mar
        update_balrog_manifest: true
        from_buildid: ${from_buildid}
        destinations:
            by-locale:
                en-US:
                    - partials/${year}/${month}/${upload_date}-${branch}
                default:
                    - partials/${year}/${month}/${upload_date}-${branch}-l10n
