# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
# This file contains exhaustive information about all the release artifacts that
# are needed within a type of release.
#
# Structure
# --------
# `bucket_paths`          -- prefix to be used per product to correctly access our buckets
# `default_locales`       -- list of locales to be used when composing upstream artifacts or the list of
#                      destinations. If given an empty locale, it uses these locales instead.
# `tasktype_map`          -- mapping between task reference and task type, particularly useful when
#                      composing the upstreamArtifacts for scriptworker.
# `platform_names`        -- various platform mappings used in reckoning artifacts or other paths
# `default`               -- a default entry, which the mappings extend and override in such a way that
#                      final path full-destinations will be a concatenation of the following:
#                      `bucket_paths`, `destinations`, `locale_prefix`, `pretty_name`
# `mapping`               -- the main section defining all artifacts to be archived
#
# Per-artifact fields (used within `mapping`):
# `from`                  -- specifies the dependency(ies) from which to expect the particular artifact
# `all_locales`           -- boolean argument to specify whether that particular artifact is to be expected
#                      for all locales or just the default one
# `description`           -- brief summary of what that artifact is
# `locale_prefix`         -- prefix to be used in the final destination paths, whether that's for default locale or not
# `source_path_modifier`  -- any parent dir that might be used in between artifact prefix and filename at source location
#                            for example `public/build` vs `public/build/ach/`.
# `destinations`          -- final list of directories where to push the artifacts
# `pretty_name`           -- the final name the artifact will have at destination
# `checksums_path`        -- the name to identify one artifact within the checksums file
# `not_for_platforms`     -- filtering option to avoid associating an artifact with a specific platform
# `only_for_platforms`    -- filtering option to exclusively include the association of an artifact for a specific platform
# `partials_only`         -- filtering option to avoid associating an artifact unless this flag is present
# `update_balrog_manifest`-- flag needed downstream in beetmover jobs to reckon the balrog manifest
# `from_buildid`          -- flag needed downstream in beetmover jobs to reckon the balrog manifest

bucket_paths:
    - pub/thunderbird/candidates
default_locales:
    - en-US
tasktype_map:
    build: build
    signing: signing
    mar-signing: signing
    partials-signing: signing
    repackage: repackage
    repackage-signing: repackage
    repackage-signing-msi: repackage
    repackage-signing-shippable-l10n-msix: signing
    release-sign-and-push-langpacks: scriptworker
    repackage-deb: repackage
    repackage-deb-l10n: repackage
platform_names:
    path_platform:
        by-platform:
            linux64-shippable: 'linux-x86_64'
            linux64-asan-reporter-shippable: 'linux-x86_64-asan-reporter'
            macosx64-shippable: 'mac'
            win32-shippable: 'win32'
            win64-shippable: 'win64'
            win64-asan-reporter-shippable: 'win64-asan-reporter'
    tools_platform:
        by-platform:
            linux64-shippable: 'linux64'
            linux64-asan-reporter-shippable: 'linux-x86_64-asan-reporter'
            macosx64-shippable: 'macosx64'
            win32-shippable: 'win32'
            win64-shippable: 'win64'
            win64-asan-reporter-shippable: 'win64-asan-reporter'
    filename_platform:
        by-platform:
            linux64-shippable: 'linux64'
            linux64-asan-reporter-shippable: 'linux-x86_64-asan-reporter'
            macosx64-shippable: 'macosx64'
            win32-shippable: 'win32'
            win64-shippable: 'win64'
            win64-asan-reporter-shippable: 'win64-asan-reporter'

default: &default
    from:
        - build
    all_locales: false
    description: "TO_BE_OVERRIDDEN"
    locale_prefix: '${locale}/'
    source_path_modifier:
        by-locale:
            default: '${locale}'
            en-US: ''
    destinations:
        - ${version}-candidates/build${build_number}/${path_platform}

mapping:
    buildhub.json:
        <<: *default
        all_locales: false
        description: "Build related information to be consumed by Buildhub service"
        pretty_name: buildhub.json
        checksums_path: ${path_platform}/${locale}/buildhub.json
    target.crashreporter-symbols.zip:
        <<: *default
        description: "Crashreporter symbols to be consumed by Socorro"
        pretty_name: thunderbird-${version}.crashreporter-symbols.zip
        checksums_path: ${path_platform}/${locale}/thunderbird-${version}.crashreporter-symbols.zip
    target.json:
        <<: *default
        description: "Various compile and moz_app flags baked together in a json file"
        pretty_name: thunderbird-${version}.json
        checksums_path: ${path_platform}/${locale}/thunderbird-${version}.json
    target.mozinfo.json:
        <<: *default
        description: "Various compile and moz_app flags baked together in a json file"
        pretty_name: thunderbird-${version}.mozinfo.json
        checksums_path: ${path_platform}/${locale}/thunderbird-${version}.mozinfo.json
    target.txt:
        <<: *default
        description: "File containing buildid and revision"
        pretty_name: thunderbird-${version}.txt
        checksums_path: ${path_platform}/${locale}/thunderbird-${version}.txt
    target_info.txt:
        <<: *default
        description: "File containing the buildID"
        locale_prefix: ''
        pretty_name: ${filename_platform}_info.txt
        checksums_path: ${filename_platform}_info.txt
        destinations:
            - ${version}-candidates/build${build_number}
    mozharness.zip:
        <<: *default
        description: "File containing the mozharness set of scripts and configuration used by various automation tools"
        pretty_name: mozharness.zip
        checksums_path: ${path_platform}/${locale}/mozharness.zip
    target.jsshell.zip:
        <<: *default
        description: "Set of shells to allow test snippets of Javascript code without needing to reload the page"
        locale_prefix: ''
        pretty_name: jsshell-${path_platform}.zip
        checksums_path: jsshell/jsshell-${path_platform}.zip
        destinations:
            - ${version}-candidates/build${build_number}/jsshell
    target.langpack.xpi:
        <<: *default
        all_locales: true
        description: "Localized repack that grabs a packaged en-US Thunderbird and repackages it as locale-specific Thunderbird"
        locale_prefix: ''
        from:
            - build
        only_for_platforms:
            - linux64-shippable
            - macosx64-shippable
            - win32-shippable
            - win64-shippable
        pretty_name: ${locale}.xpi
        checksums_path: ${path_platform}/xpi/${locale}.xpi
        destinations:
            - ${version}-candidates/build${build_number}/${path_platform}/xpi
    target.langpack.deb:
        <<: *default
        all_locales: true
        description: "langpack.xpi repackaged as a .deb"
        locale_prefix: ''
        from:
            - repackage-deb-l10n
        only_for_platforms:
            - linux-shippable
            - linux64-shippable
        pretty_name: ${locale}.deb
        checksums_path: ${path_platform}/deb-l10n/${locale}.deb
        destinations:
            - ${version}-candidates/build${build_number}/${path_platform}/deb-l10n
        update_balrog_manifest: false
    mar:
        <<: *default
        description: "Alongside `mbsdiff`, a tool used to generate partials"
        locale_prefix: ''
        source_path_modifier: 'host/bin'
        pretty_name: ${tools_platform}/mar
        checksums_path: mar-tools/${tools_platform}/mar
        not_for_platforms:
            - win32-shippable
            - win64-shippable
        destinations:
            - ${version}-candidates/build${build_number}/mar-tools
    mbsdiff:
        <<: *default
        description: "Alongside `mar`, a tool used to generate partials"
        locale_prefix: ''
        source_path_modifier: 'host/bin'
        pretty_name: ${tools_platform}/mbsdiff
        checksums_path: mar-tools/${tools_platform}/mbsdiff
        not_for_platforms:
            - win32-shippable
            - win64-shippable
        destinations:
            - ${version}-candidates/build${build_number}/mar-tools
    target.tar.xz:
        <<: *default
        description: "Main installer for Linux platforms"
        all_locales: true
        from:
            - signing
        only_for_platforms:
            - linux64-shippable
        pretty_name: thunderbird-${version}.tar.xz
        checksums_path: ${path_platform}/${locale}/thunderbird-${version}.tar.xz
    target.tar.xz.asc:
        <<: *default
        description: "Detached signature for the checksums file"
        all_locales: true
        from:
            - signing
        only_for_platforms:
            - linux64-shippable
        pretty_name: thunderbird-${version}.tar.xz.asc
        checksums_path: ${path_platform}/${locale}/thunderbird-${version}.tar.xz.asc
    target.pkg:
        <<: *default
        description: "Main package installer for Mac OS X platforms"
        all_locales: true
        from:
            - signing
        only_for_platforms:
            - macosx64-shippable
        pretty_name: Thunderbird ${version}.pkg
        checksums_path: ${path_platform}/${locale}/Thunderbird ${version}.pkg
    target.dmg:
        <<: *default
        description: "Main package installer for Mac OS X platforms"
        all_locales: true
        from:
            - repackage
        only_for_platforms:
            - macosx64-shippable
        pretty_name: Thunderbird ${version}.dmg
        checksums_path: ${path_platform}/${locale}/Thunderbird ${version}.dmg
    target.zip:
        <<: *default
        description: "Main package installer for Windows platforms"
        all_locales: true
        from:
            - signing
        only_for_platforms:
            - win64-shippable
            - win32-shippable
        pretty_name: thunderbird-${version}.zip
        checksums_path: ${path_platform}/${locale}/thunderbird-${version}.zip
    target.installer.exe:
        <<: *default
        description: "Main installer for Windows platforms"
        all_locales: true
        from:
            - repackage-signing
        only_for_platforms:
            - win64-shippable
            - win32-shippable
        pretty_name: Thunderbird Setup ${version}.exe
        checksums_path: ${path_platform}/${locale}/Thunderbird Setup ${version}.exe
    target.installer.msi:
        <<: *default
        description: "Windows installer for MSI platform"
        all_locales: true
        from:
            - repackage-signing-msi
        only_for_platforms:
            - win64-shippable
            - win32-shippable
        pretty_name: Thunderbird Setup ${version}.msi
        checksums_path: ${path_platform}/${locale}/Thunderbird Setup ${version}.msi
    target.installer.msix:
        <<: *default
        description: "Windows MSIX installer"
        from:
            - repackage-signing-shippable-l10n-msix
        only_for_platforms:
            - win64-shippable
            - win32-shippable
        locale_prefix: 'multi/'
        pretty_name: Thunderbird Setup ${version}.msix
        checksums_path: ${path_platform}/multi/Thunderbird Setup ${version}.msix
    target.deb:
        <<: *default
        description: "Thunderbird as a .deb package"
        only_for_platforms:
            - linux64-shippable
        pretty_name: thunderbird-${version}.deb
        checksums_path: ${path_platform}/${locale}/thunderbird-${version}.deb
        from:
            - repackage-deb
        update_balrog_manifest: false
    target.complete.mar:
        <<: *default
        description: "Complete MAR to serve as updates"
        all_locales: true
        from:
            - mar-signing
        pretty_name: thunderbird-${version}.complete.mar
        checksums_path: update/${path_platform}/${locale}/thunderbird-${version}.complete.mar
        update_balrog_manifest: true
        destinations:
            - ${version}-candidates/build${build_number}/update/${path_platform}
    ${partial}:
        <<: *default
        description: "Partials MAR files to serve as updates"
        all_locales: true
        from:
            - partials-signing
        partials_only: true
        pretty_name: thunderbird-${previous_version}-${version}.partial.mar
        checksums_path: update/${path_platform}/${locale}/thunderbird-${previous_version}-${version}.partial.mar
        update_balrog_manifest: true
        from_buildid: ${from_buildid}
        destinations:
            - ${version}-candidates/build${build_number}/update/${path_platform}
